name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 */1 * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base_branch: master
            upstream_branch: master
            ff_only: false
          - base_branch: upstream
            upstream_branch: master
            ff_only: true
          # Add more combinations as desired
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.base_branch }}
          fetch-depth: 0 # Fetch all history to allow merge without history error
          token: ${{ secrets.SYNC_TOKEN }}

      - name: Fetch Upstream
        run: |
          git config --local user.email "[hidden]"
          git config --local user.name "CI"
          git remote add upstream https://github.com/comfyanonymous/ComfyUI.git
          git fetch upstream
          if [ ${{ matrix.ff_only }} == "true" ]; then
            git merge --ff-only upstream/${{ matrix.upstream_branch }}
          else
            git merge upstream/${{ matrix.upstream_branch }}
          fi
          git push
